{% set name = "microlens-submit" %}
{% set filename_name = name | replace("-", "_") %}
{% set version = "0.16.4" %}
{% set python_min = "3.10" %}

# NOTE: This recipe is the source of truth for conda-forge. Edit it here in
# microlens-submit and let the release workflow sync it to the feedstock.

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ filename_name }}-{{ version }}.tar.gz
  sha256: 96c991699dbc2733e778c4a08028f1441e9a9538651f7278d8b7d8bd1ddfb4e8

build:
  number: 0
  noarch: python
  entry_points:
    - microlens-submit = microlens_submit.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pydantic >=2.0.0
    - psutil >=5.9.0
    - typer >=0.9.0
    - rich >=13.0.0
    - pyyaml >=6.0
    - markdown >=3.4.0
    - importlib_resources >=1.0.0

test:
  commands:
    - microlens-submit --help
    - python -c "import microlens_submit; import microlens_submit.cli"
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AmberLee2427/microlens-submit
  license: MIT
  license_file: LICENSE
  summary: A tool for managing and submitting microlensing solutions
  description: |
    microlens-submit provides a Python API and CLI for managing submissions
    to microlensing data challenges, including validation, dossier generation,
    and export tooling.

extra:
  recipe-maintainers:
    - AmberLee2427
